title: The Essential Worker
description: A dispatch for the rapidly radicalizing

#url: ""
#baseurl: ""

navbar-links:
  About: "about"

author:
  name: The Essential Worker

social-network-links:
  rss: true
  #email: "someone@example.com"

paginate: 5
excerpt_length: 50

title-separator: "-"
permalink: /:year-:month-:day-:title/

date_format: "%B %-d, %Y"
timezone: "America/New_York"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
